 Pandas — Series, DataFrame, eksploracja danych

Ćwiczenie 1: Series — tworzenie i operacje

In [38]:
import pandas as pd
import numpy as np

In [39]:
# Series z listy — domyślny indeks (0, 1, 2, ...)
oceny = pd.Series([4.5, 3.0, 5.0, 3.5, 4.0])
print(oceny)

0    4.5
1    3.0
2    5.0
3    3.5
4    4.0
dtype: float64

In [40]:
# Klucze: 'Anna', 'Jan', 'Ewa', 'Marek', 'Kasia'
# Wartości: 5500, 7200, 4800, 9100, 6300
pensja = {'Anna': 5500,
          'Jan': 7200,
          'Ewa': 4800,
          'Marek': 9100,
          'Kasia': 6300}

pensje = pd.Series(pensja)

In [41]:
# 1. Wyświetl imię osoby zarabiającej najwięcej (użyj idxmax())
# 2. Oblicz średnią pensję
# 3. Wyświetl imiona osób zarabiających powyżej średniej (filtrowanie boolean)
# 4. Policz ile osób zarabia poniżej 6000 (użyj len() lub .sum())
#1
print(pensje.idxmax())
print(pensje[pensje.idxmax()])
print(f'Najwięcej zarabia {pensje.idxmax()}.')
#2
print(pensje.mean())
#3
imiona = [k for k, v in pensja.items() if v > pensje.mean()]
for imie in imiona:
    print(f'{imiona}')
#4

# Sposób z len() - tworzymy tymczasową listę osób spełniających warunek
liczba_len = len([imie for imie in pensja if pensja[imie] < 6000])

# Sposób z sum() - sumujemy jedynki dla każdego trafienia (bardziej eleganckie)
liczba_sum = sum(1 for kwota in pensja.values() if kwota < 6000)

print(f"Liczba osób zarabiających poniżej 6000: {liczba_sum}")

Marek
9100
Najwięcej zarabia Marek.
6580.0
['Jan', 'Marek']
['Jan', 'Marek']
Liczba osób zarabiających poniżej 6000: 2

In [42]:
# 1. Oblicz pensje po podwyżce 10% dla wszystkich (pensje * 1.10)
# 2. Oblicz pensje po premii 500 zł dla wszystkich (pensje + 500)
# 3. Oblicz nową pensję = (pensja * 1.10) + 500
# 4. Wyświetl ranking nowych pensji od najwyższej (użyj sort_values)
#1
print(pensje * 1.10)
#2
print(pensje + 500)
#3
print(pensje *  1.10 + 500)

Anna      6050.0
Jan       7920.0
Ewa       5280.0
Marek    10010.0
Kasia     6930.0
dtype: float64
Anna     6000
Jan      7700
Ewa      5300
Marek    9600
Kasia    6800
dtype: int64
Anna      6550.0
Jan       8420.0
Ewa       5780.0
Marek    10510.0
Kasia     7430.0
dtype: float64

In [43]:
#4
nowe_pensje = pensje *  1.10 + 500
ranking = nowe_pensje.sort_values(ascending= False)
print(ranking)

Marek    10510.0
Jan       8420.0
Kasia     7430.0
Anna      6550.0
Ewa       5780.0
dtype: float64

Ćwiczenie 2: DataFrame — tworzenie i atrybuty

In [44]:
# Dane o produktach sklepu internetowego
sklep = pd.DataFrame({
'produkt': ['Laptop', 'Tablet', 'Smartfon', 'Słuchawki', 'Monitor'],
'cena': [3500, 1800, 2500, 350, 2200],
'stan_magazynowy': [45, 120, 200, 500, 75],
'kategoria': ['Komputery', 'Mobilne', 'Mobilne', 'Akcesoria', 'Komputery']
})

In [45]:
# 1. Wyświetl kształt tabeli (shape)
print(sklep.shape)
# 2. Wyświetl nazwy kolumn (columns)
print(sklep.columns)
# 3. Wyświetl typy danych w każdej kolumnie (dtypes)
print(sklep.dtypes)
# 4. Wyświetl pierwsze 3 wiersze (head)
print(sklep.head(3))

(5, 4)
Index(['produkt', 'cena', 'stan_magazynowy', 'kategoria'], dtype='str')
produkt              str
cena               int64
stan_magazynowy    int64
kategoria            str
dtype: object
    produkt  cena  stan_magazynowy  kategoria
0    Laptop  3500               45  Komputery
1    Tablet  1800              120    Mobilne
2  Smartfon  2500              200    Mobilne

In [46]:
# 1. Dodaj kolumnę 'wartosc_magazynu' = cena * stan_magazynowy
sklep['wartość_magazynu'] = sklep['cena'] * sklep['stan_magazynowy']
print(sklep)
# 2. Dodaj kolumnę 'cena_z_vat' = cena * 1.23
sklep['cena_z_VAT'] = sklep['cena'] * 1.23
# 3. Wyświetl cały DataFrame z nowymi kolumnami
print(sklep)

     produkt  cena  stan_magazynowy  kategoria  wartość_magazynu
0     Laptop  3500               45  Komputery            157500
1     Tablet  1800              120    Mobilne            216000
2   Smartfon  2500              200    Mobilne            500000
3  Słuchawki   350              500  Akcesoria            175000
4    Monitor  2200               75  Komputery            165000
     produkt  cena  stan_magazynowy  kategoria  wartość_magazynu  cena_z_VAT
0     Laptop  3500               45  Komputery            157500      4305.0
1     Tablet  1800              120    Mobilne            216000      2214.0
2   Smartfon  2500              200    Mobilne            500000      3075.0
3  Słuchawki   350              500  Akcesoria            175000       430.5
4    Monitor  2200               75  Komputery            165000      2706.0

In [47]:
# Adres URL do surowych danych CSV
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv'

# Wczytanie danych do obiektu DataFrame o nazwie tips
tips = pd.read_csv(url)

# 1. Wyświetl ile wierszy i kolumn ma dataset (shape)
tips.shape 
# 2. Wyświetl ostatnie 5 wierszy (tail)
tips.tail(5)
# 3. Wyświetl 3 losowe wiersze (sample)
tips.sample(3)
# 4. Wyświetl typy danych w każdej kolumnie (dtypes)
tips.dtypes

total_bill    float64
tip           float64
sex               str
smoker            str
day               str
time              str
size            int64
dtype: object

Ćwiczenie 3: Eksploracja datasetu — samodzielna analiza

In [48]:
url = 'https://raw.githubusercontent.com/mwaskom/seaborn-data/master/penguins.csv'
penguins = pd.read_csv(url)

In [49]:
# 1. Wyświetl head(10)
penguins.head(10)

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
0,Adelie,Torgersen,39.1,18.7,181.0,3750.0,MALE
1,Adelie,Torgersen,39.5,17.4,186.0,3800.0,FEMALE
2,Adelie,Torgersen,40.3,18.0,195.0,3250.0,FEMALE
3,Adelie,Torgersen,NaN,NaN,NaN,NaN,NaN
4,Adelie,Torgersen,36.7,19.3,193.0,3450.0,FEMALE
5,Adelie,Torgersen,39.3,20.6,190.0,3650.0,MALE
6,Adelie,Torgersen,38.9,17.8,181.0,3625.0,FEMALE
7,Adelie,Torgersen,39.2,19.6,195.0,4675.0,MALE
8,Adelie,Torgersen,34.1,18.1,193.0,3475.0,NaN
9,Adelie,Torgersen,42.0,20.2,190.0,4250.0,NaN

In [50]:
# 2. Wyświetl shape
penguins.shape

(344, 7)

In [51]:
# 3. Uruchom info() — ile brakujących wartości widzisz?
(penguins['sex'].isna().sum() / len(penguins)) * 100

np.float64(3.1976744186046515)

In [52]:
# 1. Uruchom describe() — co mówią ci średnie i odchylenia?
penguins.describe()

       bill_length_mm  bill_depth_mm  flipper_length_mm  body_mass_g
count      342.000000     342.000000         342.000000   342.000000
mean        43.921930      17.151170         200.915205  4201.754386
std          5.459584       1.974793          14.061714   801.954536
min         32.100000      13.100000         172.000000  2700.000000
25%         39.225000      15.600000         190.000000  3550.000000
50%         44.450000      17.300000         197.000000  4050.000000
75%         48.500000      18.700000         213.000000  4750.000000
max         59.600000      21.500000         231.000000  6300.000000

In [53]:
# 2. Uruchom describe(include='all') — co dodają kolumny tekstowe?
penguins.describe(include= "all")

,species,island,bill_length_mm,bill_depth_mm,flipper_length_mm,body_mass_g,sex
count,344,344,342.000000,342.000000,342.000000,342.000000,333
unique,3,3,NaN,NaN,NaN,NaN,2
top,Adelie,Biscoe,NaN,NaN,NaN,NaN,MALE
freq,152,168,NaN,NaN,NaN,NaN,168
mean,NaN,NaN,43.921930,17.151170,200.915205,4201.754386,NaN
std,NaN,NaN,5.459584,1.974793,14.061714,801.954536,NaN
min,NaN,NaN,32.100000,13.100000,172.000000,2700.000000,NaN
25%,NaN,NaN,39.225000,15.600000,190.000000,3550.000000,NaN
50%,NaN,NaN,44.450000,17.300000,197.000000,4050.000000,NaN
75%,NaN,NaN,48.500000,18.700000,213.000000,4750.000000,NaN
max,NaN,NaN,59.600000,21.500000,231.000000,6300.000000,NaN

In [54]:
# 3. Jaka jest mediana masy ciała (body_mass_g)?
penguins['body_mass_g'].median()

np.float64(4050.0)

In [55]:
# 1. Ile jest pingwinów każdego gatunku? (value_counts na 'species')
penguins['species'].value_counts()

species
Adelie       152
Gentoo       124
Chinstrap     68
Name: count, dtype: int64

In [56]:
# 2. Ile pingwinów na każdej wyspie? (value_counts na 'island')
penguins['island'].value_counts

<bound method IndexOpsMixin.value_counts of 0      Torgersen
1      Torgersen
2      Torgersen
3      Torgersen
4      Torgersen
         ...
339       Biscoe
340       Biscoe
341       Biscoe
342       Biscoe
343       Biscoe
Name: island, Length: 344, dtype: str>

In [57]:
# 3. Rozkład płci (value_counts na 'sex') — czy jest zbalansowany?
penguins['sex'].value_counts

<bound method IndexOpsMixin.value_counts of 0        MALE
1      FEMALE
2      FEMALE
3         NaN
4      FEMALE
        ...
339       NaN
340    FEMALE
341      MALE
342    FEMALE
343      MALE
Name: sex, Length: 344, dtype: str>

In [58]:
# 4. Jaki procent to gatunek Adelie? (normalize=True)
penguins['species'].value_counts(normalize=True)

species
Adelie       0.441860
Gentoo       0.360465
Chinstrap    0.197674
Name: proportion, dtype: float64

In [59]:
# 1. Policz brakujące wartości w każdej kolumnie (isna().sum())
penguins.isna().sum()

species               0
island                0
bill_length_mm        2
bill_depth_mm         2
flipper_length_mm     2
body_mass_g           2
sex                  11
dtype: int64

In [60]:
# 2. Jaki procent danych brakuje w kolumnie 'sex'?
# Podpowiedź: braki / len(penguins) * 100
(penguins['sex'].isna().sum() / len(penguins)) * 100

np.float64(3.1976744186046515)

Ćwiczenie 4: Pytania biznesowe + commit

In [61]:
tips = pd.read_csv('https://raw.githubusercontent.com/mwaskom/seaborn-data/master/tips.csv')
# Dodaj kolumnę z procentem napiwku
tips['tip_pct'] = (tips['tip'] / tips['total_bill'] * 100).round(1)

In [ ]:
# 1. Oblicz średni rachunek (total_bill)
print(tips['total_bill'].mean())
# 2. Oblicz średni napiwek w procentach (tip_pct)
print(tips['tip_pct'].mean())
# 3. Wyświetl który dzień ma najwięcej rachunków (value_counts na 'day')
print(tips['day'].value_counts())
# 4. Policz ile rachunków jest od palaczy (value_counts na 'smoker')
print(tips['smoker'].value_counts())
# 5. Wyświetl describe() tylko dla kolumny 'tip' — jaka jest mediana napiwku?
print(tips['tip'].describe())
# 6. Jaki procent rachunków pochodzi z obiadu (Dinner)?
print(tips['time'].value_counts(normalize=True))
# Podpowiedź: value_counts(normalize=True) na kolumnie 'time'
# 7. Ile unikalnych rozmiarów grup jest w danych? (nunique na 'size')
print(tips['size'].nunique())

19.78594262295082
16.08155737704918
day
Sat     87
Sun     76
Thur    62
Fri     19
Name: count, dtype: int64
smoker
No     151
Yes     93
Name: count, dtype: int64
count    244.000000
mean       2.998279
std        1.383638
min        1.000000
25%        2.000000
50%        2.900000
75%        3.562500
max       10.000000
Name: tip, dtype: float64